name: assets_gen
executables:
  assets_gen:
description: A sample command-line application.
version: 0.0.1+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  yaml: ^2.2.1
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
