name: assets_gen
executables:
  assets_gen:
description: A sample command-line application.
version: 0.3.0+4
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.0'

dependencies:
  yaml: ^3.1.2
  code_builder: ^4.6.0
  dart_style: ^2.3.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6


