name: assets_gen
executables:
  assets_gen:
description: A sample command-line application.
version: 0.2.0+3
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.1
  code_builder: ^4.4.0
  dart_style: ^2.2.4
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2


