name: assets_gen
executables:
  assets_gen:
description: A sample command-line application.
version: 0.1.0+2
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  code_builder: ^4.1.0
  dart_style: ^2.2.2
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1


